services:
  - type: web
    name: kaveri-admission-backend
    runtime: node
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"

  - type: static
    name: kaveri-admission-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: kaveri-admission-backend
          property: host
